"""Test-only stand-ins for an external grader and a reviewed calibration record.

These are neither released instruments nor empirical calibration evidence. The grader accepts only
the tiny addition language generated by this test suite, and never executes submitted Python.
The calibration counts below are invented fixture data for exercising acceptance and refusal paths.
"""
import ast
from functools import lru_cache

from arc_runner import custody
from arc_runner import calibration_gate as CG
from arc_runner import observation as OBS


def trusted_addition_batch_runner():
    @lru_cache(maxsize=512)
    def grade(text, entries):
        try:
            tree = ast.parse(text)
        except SyntaxError:
            return set()
        namespace = {}
        args = ast.dump(ast.parse("def f(x, y): pass").body[0].args)
        addition = ast.dump(ast.parse("x + y", mode="eval").body)
        for node in tree.body:
            if (not isinstance(node, ast.FunctionDef) or node.decorator_list
                    or len(node.body) != 1 or not isinstance(node.body[0], ast.Return)
                    or ast.dump(node.args) != args):
                return set()
            value = node.body[0].value
            if ast.dump(value) == addition:
                namespace[node.name] = lambda x, y: x + y
            elif isinstance(value, ast.Constant) and value.value is None:
                namespace[node.name] = lambda x, y: None
            else:
                return set()
        passed = set()
        for item_id, checks in entries:
            try:
                for check in checks:  # trusted, authored fixture assertions only
                    exec(check, dict(namespace))
                passed.add(item_id)
            except Exception:
                pass
        return passed
    def run(text, items):
        return set(grade(text, tuple((i.id, tuple(i.checks)) for i in items)))
    return custody.attest_exact_check(run)


def with_fixture_calibration(cfg):
    quantities = [OBS.BALANCE_ELASTICITY, OBS.SERVICE_RATIO, OBS.LOG_SERVICE_RATIO]
    cfg.alarm_rate_null_calibration = {
        "schema": CG.SCHEMA, "configuration_sha256": CG.configuration_digest(cfg),
        "code_sha256": custody.package_code_identity(), "endpoint": "P16", "unit": "whole_run",
        "registration": "test-only invented registration",
        "evidence_uri": "test-only:invented-counts", "evidence_sha256": "a" * 64,
        "reviewed_by": "test-only stand-in", "simultaneous_confidence": 0.95,
        "registered_error_limit": 0.05, "observation_quantities": quantities,
        "worlds": [{"quantity": q, "world": w, "world_spec_sha256": "b" * 64,
                    "independent_runs": 10000, "false_supports": 0, "false_refutations": 0}
                   for q in quantities for w in sorted(CG.REQUIRED_WORLDS)]}
    return cfg
